// rickandmorty-svelte/src/App.svelte
<script>
	import { onMount } from 'svelte';
	import Character from './Character.svelte';
	import { URL } from './constants';

	let data = {};
	let characters = [];

	const setCharacters = data => {
		characters = [...characters, ...data];
	}

	const handleClick = e => {
		if (data.info.next === '') return
		fetchData(data.info.next);
	}

	const fetchData = async (url = URL) => {
		try {
			const r = await fetch(url);
			data = await r.json();

			setCharacters(data.results);
		} catch(e) {
			console.error(e);
		}
	}

	onMount(fetchData)
</script>

<div class="characters">
	{#each characters as c}
		<Character name={c.name} image={c.image} />
	{:else}
		<p>loading...</p>
	{/each}
	{#if characters.length > 0 && data.info.next !== ''}
		<button on:click={handleClick}>
			Add more
		</button>
	{/if}
</div>

<style>
	.characters {
		width: 100%;
		display: grid;
		grid-template-columns: repeat(5, 1fr);
		grid-gap: 8px;
	}
</style>

// rickandmorty-react/src/App.js
import React from 'react';
import './App.css';
import Character from './Character';
import { URL } from './constants';

function App() {
  const [characters, setCharacters] = React.useState([]);
  const [data, setData] = React.useState({});

  const fetchData = async (url = URL) => {
    try {
      const r = await fetch(url);
      const data = await r.json();

      setData(data);
      setCharacters([...characters, ...data.results]);
    } catch (e) {
      console.error(e);
    }
  }

  const handleClick = () => {
    if (data.info.next === '') return
    fetchData(data.info.next);
  }

  React.useEffect(() => {fetchData()}, []);

  return (
    <div className="characters">
      { characters.length === 0
        ? <p>loading...</p>
        : characters.map((e, i) => <Character key={i} {...e} />)
      }
      { characters.length !== 0 && data.info.next !== ''
        ? <button onClick={handleClick}>
            Add more
          </button>
        : null
      }
    </div>
  );
}

export default App;
